language: php
php:
    - 5.6
    - 5.5
    - 5.4
branches:
    only:
        - master
before_install:
    - composer install
script:
    - php bin/phing -f build/build.xml
after_script:
    - bin/test-reporter --stdout > codeclimate.json
    - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
cache:
    directories:
        - vendor/
