language: php
php:
    - 5.6
    - 5.5
    - 5.4
branches:
    only:
        - master
before_install:
    - composer install
script:
    - php bin/phing -f build/build.xml
cache:
    directories:
        - vendor/
